version: '3'
services:
  web:
    image: nginx:1.15-alpine
    ports: 
      - 2000:80
    volumes:
      - ./web:/usr/share/nginx/html
  api:
    build:
      context: ./
      dockerfile: _api.Dockerfile
    ports:
      - 2001:80
    volumes:
      - ./api:/var/www/html/
    # command: composer install
