version: 2

jobs:
  build-job:
    docker:
      - image: circleci/php:7.2-apache-node-browsers-legacy
    working_directory: ~/wu2018
    steps:
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php -- --filename=composer
      - run: ./composer install
      - run: ./vendor/bin/phpunit