version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-browsers

    working_directory: ~/fan-finder
    steps:
      - checkout
      - run: cd api && ls
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "api/composer.json" }}
          - v1-dependencies-
      - run: cd api && composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./api/vendor
          key: v1-dependencies-{{ checksum "api/composer.json" }}
      - run: wget https://phar.phpunit.de/phpunit-6.5.phar
      - run: chmod +x phpunit-6.5.phar
      - run: mv phpunit-6.5.phar ./api/phpunit
      - run: cd api && ./phpunit

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Update code
          command: ssh $DROPLET_USER@$DROPLET_IP "cd /root/fan-finder_$CIRCLE_BRANCH; git pull"
      - run:
          name: Re-build services in docker containers
          command: ssh $DROPLET_USER@$DROPLET_IP "cd /root/fan-finder_$CIRCLE_BRANCH; docker-compose up --build -d"
      - run: echo "docker exec fanfinder$CIRCLE_BRANCH_api_1 composer install"
      - run:
          name: Install PHP dependencies
          command: ssh $DROPLET_USER@$DROPLET_IP "cd /root/fan-finder_$CIRCLE_BRANCH; docker exec fanfinder$CIRCLE_BRANCH_api_1 composer install"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
