version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-browsers

    working_directory: ~/fan-finder
    steps:
      - checkout
      - run: cd api && ls
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "api/composer.json" }}
          - v1-dependencies-
      - run: cd api && composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./api/vendor
          key: v1-dependencies-{{ checksum "api/composer.json" }}
      - run: wget https://phar.phpunit.de/phpunit-6.5.phar
      - run: chmod +x phpunit-6.5.phar
      - run: mv phpunit-6.5.phar /usr/local/bin/phpunit
      - run: cd api && phpunit