version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-browsers

    working_directory: ~/fan-finder
    steps:
      - checkout
      - run: cd api && ls
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "api/composer.json" }}
          - v1-dependencies-
      - run: cd api && composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./api/vendor
          key: v1-dependencies-{{ checksum "api/composer.json" }}
      - run: wget https://phar.phpunit.de/phpunit-6.5.phar
      - run: chmod +x phpunit-6.5.phar
      - run: mv phpunit-6.5.phar ./api/phpunit
      - run: cd api && ./phpunit

  deployment:
    steps:
      - run: echo 'deploying'
      - run: ssh -v $DROPLET_USER@$DROPLET_IP "cd /root/fan-finder_$CIRCLE_BRANCH; docker-compose up --build -d"
      - run: ssh -v $DROPLET_USER@$DROPLET_IP "cd /root/fan-finder_$CIRCLE_BRANCH; docker exec fanfinder$CIRCLE_BRANCH_api_1 composer install"
