version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-browsers

    working_directory: ~/fan-finder
    steps:
      - checkout
      - run: cd api && ls
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: cd api && composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: cd api && phpunit